version: "3.7"

services:
  elasticsearch:
    env_file: ./defaults.env
    container_name: elasticsearch
    image: gcr.io/spacemesh-198810/elasticsearch:7.5.1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      # - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
    ports:
      - 9200:9200
    restart: on-failure
  
  kibana:
    container_name: kibana
    env_file: ./defaults.env
    image: gcr.io/spacemesh-198810/kibana:7.5.1
    ports: 
      - 5601:5601

  fluentbit:
    container_name: fluentbit
    env_file: ./defaults.env
    image: fluent/fluent-bit
    volumes:
      - ./config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - 24224:24224
      - 24224:24224/udp
      
  grafana:
    container_name: grafana
    image: grafana/grafana
    env_file: ./defaults.env
    environment:
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - 3000:3000

volumes:
  es_data:
