{
 "title": "Spacemesh Dashbaord",
 "description": "some basic node/network health stuff",
 "tags": [ "elasticsearch" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "P2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bootstrapped",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "T", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "log: \"{M: \\\"discovery_bootstrap\\\"}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Gossip messages",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spacemesh_p2p_total_gossip_messages{container_name: \"$instance\"}"
    }
   ]
  },
  { "title": "Spacemesh", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Latest Layer",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "format": "locale",
   "valueName": "max",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "layer_id",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "layer_id",
       "id": "1",
       "meta": {
        "std_deviation_bounds_lower": true,
        "std_deviation_bounds_upper": false
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "container_name: \"$instance\" AND log: \"{M: \\\"release tick\\\"}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "content": "## Todo\n\nExpsoe `config` with a metric or log. (with `layers_per_epoch` we could calculate `epoch_id` )\n\n\n"
  },
  {
   "title": "ATX published",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "T", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "container_name: \"$instance\" AND log: \"{M: \\\"got new atx\\\"}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "pBase",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pBase",
     "bucketAggs": [
      { "field": "T", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pbase",
       "id": "3",
       "meta": {
        "std_deviation": false,
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": true
       },
       "settings": {
        "missing": null
       },
       "type": "extended_stats"
      }
     ],
     "query": "container_name: \"$instance\" AND log: \"{M: \\\"Tortoise finished layer\\\"}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "got new block",
     "bucketAggs": [
      { "field": "T", "id": "2", "settings": { "interval": "2m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pbase",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "container_name: \"$instance\" AND log: \"{M: \\\"got new block\\\"}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hare",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "alias": "Start",
     "bucketAggs": [
      { "field": "layer_id", "id": "2", "settings": { "interval": 1, "min_doc_count": 1 }, "type": "histogram" }
     ],
     "metrics": [
      {
       "field": "T",
       "id": "4",
       "meta": {
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "container_name: \"$instance\" AND log: \"{M: \\\"Consensus Process Started\\\"}\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Terminate",
     "bucketAggs": [
      { "field": "layer_id", "id": "2", "settings": { "interval": 1, "min_doc_count": 1 }, "type": "histogram" }
     ],
     "metrics": [
      {
       "field": "T",
       "id": "3",
       "meta": {
        "std_deviation_bounds_lower": true,
        "std_deviation_bounds_upper": false
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "container_name: \"$instance\" AND log: \"{M: \\\"Consensus Process terminated\\\"}\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "container_name: \"$instance\" AND log: \"{L: \\\"ERROR\\\"}\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}