{
 "title": "Go Metrics",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang",
  "elasticsearch"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Number of live instances",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count({job=\"prometheus\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Top Instances",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "topk(300, go_memstats_sys_bytes{})",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spacemesh_p2p_peers{instance=~\"$instance\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_alloc_bytes"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_sys_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_idle_bytes"
    },
    {
     "expr": "go_memstats_heap_released_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_released_bytes"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{instance=~\"$instance\"} - go_memstats_other_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {instance={{instance}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{instance=~\"$instance\"} - go_memstats_frees_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}"
    },
    {
     "expr": "go_threads{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "allocations"
    }
   ]
  }
 ]
}