apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: ${COMPOSE_PROJECT_NAME}
    jsonData:
      timeField: "@timestamp"
      esVersion: 70
