filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            equals:
              docker.container.labels.app: go-spacemesh
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              json.keys_under_root: true
              json.overwrite_keys: true
              json.add_error_key: false
              json.ignore_decoding_error: true
              processors:
                - add_docker_metadata:
                    host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_URL}:9200"]
  indices:
    - index: "sm-%{+yyyy.MM.dd-HH:mm}"

logging.json: true
logging.metrics.enabled: false
