global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus

    scrape_interval: 5s
    scrape_timeout: 2s

    static_configs:
      - targets:
        - 'bs_node:2020'

    dns_sd_configs:
      - names:
        - node
        type: 'A'
        port: 2020
        
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):\\d+"
        target_label: instance
        replacement: "/${1}"
